name: My First GitHub Action
on: [push]
jobs:
    test:
        runs-on: ubuntu-16.04
        steps:
          - name: Checkout source code
            uses: actions/checkout@v2
          - name: install Node
            uses: actions/setup-node@v2
            with: 
                node—version: 14
          - name: run node
            run: node -v
